#!/usr/bin/env bash
#Create a function that that will display info about the subdomains

display_info{
	local domain = $1
	local subdomain= $2

	subdomain_list = ("www" "lb-01" "web-01" "web-02")

	for sub in "$subdomain_list[@]"; do
	    get_info = $(dig "$2"."$1" | grep -A1 'ANSWER SECTION' {getline; print}') 
}
