#!/usr/bin/env bash
#Install updates
sudo apt install update
sudo apt install -y nginx
#write a custom HTML file
echo "Hello World!" | sudo tee /var/www/html/index.html

#configure nginx to use the custom html file

sudo bash -c "echo 'server {
    listen 80 default_server;
    listen [::]:80 default_server ipv6only=on;

    root /var/www/html;

    index index.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }
}' > /etc/nginx/sites-available/default"

# Remove the default symbolic link in sites-enabled
sudo rm -f /etc/nginx/sites-enabled/default

# Create a new symbolic link to the configuration file in sites-available
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Restart Nginx
sudo service nginx restart
