#!/usr/bin/env bash
# configures a new Ubuntu machine

# Install nginx on web-01 server
sudo apt-get -y update
sudo apt-get -y install nginx

# Add custom response header to know the server name for debugging
HOST_NAME=$(hostname)
HEADER="add_header X-Served-By $HOST_NAME;"
FIND=$(grep "X-Served-By" /etc/nginx/sites-available/default)
if [[ -z $FIND ]]; then
    echo "Adding header to Nginx configuration"
    sudo sed -i "/server_name _;/a \\\t$HEADER" /etc/nginx/sites-available/default
fi

# Create a firts index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Add to the nginx configuration file a redirection to another page
FIND=$(grep "redirect_me" /etc/nginx/sites-available/default)
STRING="\\\n\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=3MbaGJN2ioQ;\n\t}\n"
if [[ -z $FIND ]]; then
    sudo sed -i "/server_name _;/a $STRING" /etc/nginx/sites-available/default
fi

# Add to the nginx configuration file a error page 404
FIND=$(grep "error_page 404" /etc/nginx/sites-available/default)
ERROR="\\\n\terror_page 404 /custom_404.html;\n"
if [[ -z $FIND ]]; then
    echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
    sudo sed -i "/server_name _;/a $ERROR" /etc/nginx/sites-available/default
fi

#restart the nginx server to apply changes
sudo service nginx restart
